---
on:
  push:
    branches:
      # - main
  pull_request:

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.13'
          - '3.12'
          - '3.11'
          - '3.10'
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python }}
      
      # Quality
      - name: Test with python ${{ matrix.python }}
        run: uv run --frozen pytest
      - name: Lint
        run: make lint
      - name: Type check
        run: make type-check

      # Packaging
      - name: Build packages
        run: uv build

